# -*- coding: utf-8 -*-

"""
    codegenandtransformerapi.models.format

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class Format(object):

    """Implementation of the 'format' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_API BLUEPRINT: TODO: type description here.
        ENUM_GOOGLE DISCOVERY: TODO: type description here.
        RAML: TODO: type description here.
        WADL: TODO: type description here.
        SWAGGER: TODO: type description here.
        ENUM_IO DOCS: TODO: type description here.
        APIMATIC: TODO: type description here.
        WSDL: TODO: type description here.
        MASHAPE: TODO: type description here.
        POSTMAN: TODO: type description here.
        HAR: TODO: type description here.
        OPEN API SPEC 300 RC1: TODO: type description here.

    """

    ENUM_API_BLUEPRINT = 'API Blueprint'

    ENUM_GOOGLE_DISCOVERY = 'Google Discovery'

    RAML = 'RAML'

    WADL = 'WADL'

    SWAGGER = 'Swagger'

    ENUM_IO_DOCS = 'IO Docs'

    APIMATIC = 'APIMATIC'

    WSDL = 'WSDL'

    MASHAPE = 'Mashape'

    POSTMAN = 'Postman'

    HAR = 'HAR'

    OPEN_API_SPEC_300_RC1 = 'OpenApi3'

