# -*- coding: utf-8 -*-

"""
    codegenandtransformerapi.models.format_transformer

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class FormatTransformer(object):

    """Implementation of the 'format_transformer' enum.

    TODO: type enum description here.

    Attributes:
        APIMATIC: TODO: type description here.
        WADL2009: TODO: type description here.
        SWAGGER10: TODO: type description here.
        SWAGGER20: TODO: type description here.
        SWAGGERYAML: TODO: type description here.
        APIBLUEPRINT: TODO: type description here.
        RAML: TODO: type description here.

    """

    APIMATIC = 'apimatic'

    WADL2009 = 'wadl2009'

    SWAGGER10 = 'swagger10'

    SWAGGER20 = 'swagger20'

    SWAGGERYAML = 'swaggeryaml'

    APIBLUEPRINT = 'apiblueprint'

    RAML = 'raml'

