# -*- coding: utf-8 -*-

"""
    codegenandtransformerapi.models.template

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class Template(object):

    """Implementation of the 'template' enum.

    TODO: type enum description here.

    Attributes:
        CS_PORTABLE_NET_LIB: TODO: type description here.
        JAVA_ECLIPSE_JRE_LIB: TODO: type description here.
        JAVA_GRADLE_ANDROID_LIB: TODO: type description here.
        OBJC_COCOA_TOUCH_IOS_LIB: TODO: type description here.
        ANGULAR_JAVASCRIPT_LIB: TODO: type description here.
        RUBY_GENERIC_LIB: TODO: type description here.
        ENUM_PYTHON_GENERIC_LIB: TODO: type description here.
        ENUM_PHP_GENERIC_LIB: TODO: type description here.
        ENUM_NODE_JAVASCRIPT_LIB: TODO: type description here.
        ENUM_GO_GENERIC_LIB: TODO: type description here.

    """

    CS_PORTABLE_NET_LIB = 'cs_portable_net_lib'

    JAVA_ECLIPSE_JRE_LIB = 'java_eclipse_jre_lib'

    JAVA_GRADLE_ANDROID_LIB = 'java_gradle_android_lib'

    OBJC_COCOA_TOUCH_IOS_LIB = 'objc_cocoa_touch_ios_lib'

    ANGULAR_JAVASCRIPT_LIB = 'angular_javascript_lib'

    RUBY_GENERIC_LIB = 'ruby_generic_lib'

    ENUM_PYTHON_GENERIC_LIB = 'python_generic_lib'

    ENUM_PHP_GENERIC_LIB = 'php_generic_lib'

    ENUM_NODE_JAVASCRIPT_LIB = 'node_javascript_lib'

    ENUM_GO_GENERIC_LIB = 'go_generic_lib'

