# -*- coding: utf-8 -*-

"""
    codegenandtransformerapi.models.validate_an_api_description_response

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class ValidateAnAPIDescriptionResponse(object):

    """Implementation of the 'Validate an API description response' model.

    TODO: type model description here.

    Attributes:
        errors (list of object): TODO: type description here.
        warnings (list of object): TODO: type description here.
        messages (list of object): TODO: type description here.
        success (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "errors" : "Errors",
        "warnings" : "Warnings",
        "messages" : "Messages",
        "success" : "Success"
    }

    def __init__(self,
                 errors=None,
                 warnings=None,
                 messages=None,
                 success=None):
        """Constructor for the ValidateAnAPIDescriptionResponse class"""

        # Initialize members of the class
        self.errors = errors
        self.warnings = warnings
        self.messages = messages
        self.success = success


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        errors = dictionary.get("Errors")
        warnings = dictionary.get("Warnings")
        messages = dictionary.get("Messages")
        success = dictionary.get("Success")

        # Return an object of this model
        return cls(errors,
                   warnings,
                   messages,
                   success)


